---
name: Python package
on:
  workflow_dispatch:
  push:
    branches: [main]
    tags: "v*"
  pull_request:
  release:
    types: [published]
jobs:
  package:
    name: Build & inspect our package.
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
        with:
          fetch-depth: 0
      - uses: hynek/build-and-inspect-python-package@v2
  publish-to-testpypi:
    name: Upload release to TestPyPI
    needs: [package]
    runs-on: ubuntu-latest
    if: github.event_name == 'push'
    environment:
      name: testpypi
      url: https://test.pypi.org/p/tilekiln
    permissions:
      id-token: write
    steps:
      - uses: actions/download-artifact@v4
        with:
          name: Packages
          path: dist
      - uses: pypa/gh-action-pypi-publish@release/v1
        with:
          repository-url: https://test.pypi.org/legacy/
          skip-existing: true

  publish-to-pypi:
    name: Publish tagged versions to PyPi
    runs-on: ubuntu-latest
    if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags')
    needs: [publish-to-testpypi]
    environment:
      name: pypi
      url: https://pypi.org/p/tilekiln
    permissions:
      id-token: write
    steps:
      - uses: actions/download-artifact@v4
        with:
          name: Packages
          path: dist
      - uses: pypa/gh-action-pypi-publish@release/v1
